import json
import logging
import shutil
from collections import defaultdict
from datetime import datetime
from pathlib import Path
from typing import Dict, List

from utils import truncate_text

logger = logging.getLogger(__name__)


def save_to_markdown(output_dir: Path, summary: str, articles: List[Dict], config: Dict) -> Path:
    """Save summary and articles to markdown file."""
    timestamp = datetime.now()
    date_str = timestamp.strftime("%Y-%m-%d")
    time_str = timestamp.strftime("%H:%M:%S")
    output_file = output_dir / f"brief_{date_str}.md"

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(f"# 📰 Daily Tech Brief\n\n")
        f.write(f"**Date**: {date_str}  \n")
        f.write(f"**Generated**: {time_str}  \n")
        f.write(f"**Total Articles**: {len(articles)}  \n")
        f.write(f"**Model**: {config['settings']['summary_model']}\n\n")
        f.write("---\n\n")

        f.write("## 🤖 AI Summary\n\n")
        f.write(summary)
        f.write("\n\n---\n\n")

        f.write("## 📋 All Articles\n\n")

        by_category = defaultdict(list)
        for article in articles:
            by_category[article['category']].append(article)

        for category, cat_articles in by_category.items():
            f.write(f"### {category}\n\n")
            for article in cat_articles:
                f.write(f"- **[{article['title']}]({article['link']})**  \n")
                f.write(f"  *{article['source']}* - {article['published']}  \n")
                f.write(f"  {truncate_text(article['summary'], 150)}\n\n")

        f.write("---\n\n")
        f.write(f"*Generated by Daily Brief Agent on {timestamp.strftime('%Y-%m-%d at %H:%M:%S')}*\n")

    logger.info(f"✓ Markdown saved to: {output_file}")
    return output_file


def save_to_json(output_dir: Path, articles: List[Dict], summary: str) -> Path:
    """Save raw data to JSON for further processing."""
    timestamp = datetime.now().strftime("%Y-%m-%d")
    output_file = output_dir / f"brief_{timestamp}.json"

    data = {
        'generated_at': datetime.now().isoformat(),
        'summary': summary,
        'article_count': len(articles),
        'articles': articles
    }

    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    logger.info(f"✓ JSON saved to: {output_file}")
    return output_file


def sync_to_vault(files: List[Path], config: Dict) -> None:
    """Copy output files to Obsidian vault if enabled."""
    vault_config = config.get('settings', {}).get('vault_sync', {})

    if not vault_config.get('enabled', False):
        return

    vault_path = vault_config.get('vault_path')
    if not vault_path:
        logger.warning("Vault sync enabled but no vault_path configured")
        return

    vault_path = Path(vault_path)
    vault_path.mkdir(parents=True, exist_ok=True)

    for source_path in files:
        if source_path and source_path.exists():
            dest_path = vault_path / source_path.name
            shutil.copy2(source_path, dest_path)
            logger.info(f"📁 Synced to Obsidian: {dest_path}")
